version: '3.9'

services:
  app1: &app
    image: rinha-2025
    hostname: app1
    environment:
      - PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
      - OTHER_INSTANCE_URL=http://app2:8080
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "160MB"

  app2:
    <<: *app
    hostname: app2
    environment:
      - PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
      - OTHER_INSTANCE_URL=http://app1:8080
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "160MB"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "30MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
    name: payment-processor